### ISSUE TITLE
This is my first time to learn this code. Could you give me a more detailed code comment?Thanks

### ISSUE THREAD

**Issue by jiaweiwangwang** [dragonbook/V2V-PoseNet-pytorch#1]

**Comment by dragonbook** [comment]
You could read the target paper(https://arxiv.org/abs/1711.07399) to get more ideas of the network and algorithm flow, it will help you quickly catch what those functions here do. Besides, this implementation has a similar structure as author'(https://github.com/mks0601/V2V-PoseNet_RELEASE), there are some implementation notes in original repository's issues, and they may be useful to you.

**Comment by jiaweiwangwang** [comment]
Thank you!
