### ISSUE TITLE
How to fit it in real industrial environment

### ISSUE THREAD

**Issue by momo1986** [dragonbook/V2V-PoseNet-pytorch#10]
Hello,
Thanks for sharing.

In real industrial environment except UYU, ICVL and MSRA datasets, gives a demo for using pretrained model with the depth image from RGBD camera?

If there exists similar Python demos, will be very great and helpful.

Thanks for reply.

Best Regards!

**Comment by dragonbook** [comment]
Hi,
I'm sorry I have no time and plan to do it. For real industrial environment(or in the wild?), there should be many works targeting on that, you can have a search. Maybe similar to paper "[Towards 3D Human Pose Estimation in the Wild: a Weakly-supervised Approach](https://arxiv.org/abs/1704.02447)" etc.
