### ISSUE TITLE
data loader for hands 2017

### ISSUE THREAD

**Issue by ibrahimrazu** [dragonbook/V2V-PoseNet-pytorch#11]
Hi, Thanks a lot for your awesome codebase. Could you please clarify the data loader for hands 2017 dataset? 
I could not find that here

**Comment by dragonbook** [comment]
Hi, there is no hands 2017 dataset loader here. It seems that the paper's author did not provide this, but you may have a request on his [repo](https://github.com/mks0601/V2V-PoseNet_RELEASE).

**Comment by ibrahimrazu** [comment]
Thanks! I will do it accordingly
