### ISSUE TITLE
Can I use ITOP dataset too?

### ISSUE THREAD

**Issue by ik8851ik** [dragonbook/V2V-PoseNet-pytorch#13]
Thank you for sharing your hard work. It has been so helpful to me.

In your implementation, I could find code for MSRA dataset only.

Are ITOP dataset, which is included in the V2V-PoseNet author's torch 7 implementation, also possible?

If it is not, can there be any critical differences I should keep in mind while implementing ITOP by myself?

Thank you so much and have a good day.

**Comment by ShuangjunLiu** [comment]
Also hope to have ITOP too.

**Comment by dragonbook** [comment]
It should be work if you write the dataset's reader and with correct configurations. You can see author's implementation and configuration for reference.
