### ISSUE TITLE
Some questions with NYU datatset

### ISSUE THREAD

**Issue by moranli19** [dragonbook/V2V-PoseNet-pytorch#6]
Thanks for your sharing.

I have changed your msra_hand.py to nyu_hand.py fitting NYU dataset and keep all other parts of your code unchanged. However, the result of NYU dataset is bad. The all mean error is 180mm after training. (epoch=14, batch_size=64, nGpus=4, optimizer =Adam, cubicSize=250, keep orignal_size and crop_size the same as yours.
While the results on NYU is about 13mm or less after epoch ensemble with nGPU=1 and batchSz=16.  

Here is my question. Why with the increase of batch size the results becoming worse? 
Is there any way to solve such a problem? 

Thanks again!

**Comment by dragonbook** [comment]
Hi, Limoran18,

I faced same situation when I train MSRA hand dataset and my own smaller dataset(not about hand) with this PyTorch implementation. I see that the author set batchSize=1 in his code. I wonder if he trained his models with the very small batchSize. I added an [issue](https://github.com/mks0601/V2V-PoseNet_RELEASE/issues/43) on his repo.

For your question, I think it's still an open question about how to set batchSize. Larger batchSize or common settings(e.g. 32, 64) may not perform that good on some models or datasets. And I noticed that some researches also show that the models trained with smaller batchSize can be more roubust and generalized. 

So, for your current model and dataset(and if they are correct), you can fine tune the hyper-parameter, or, experiment some related techniques about batchSize, e.g. [GroupNorm](https://arxiv.org/abs/1803.08494), but it's not directly related and may not help.

**Comment by dragonbook** [comment]
The author sets batchSize=8.

**Comment by moranli19** [comment]
Thanks very much for your detailed explanation!
