### ISSUE TITLE
Excuse me,I dont touch Linux System.Can Windows System run your code?I find 'stty' in progressbar.py is not available. 

### ISSUE THREAD

**Issue by Ericjiejie** [dragonbook/V2V-PoseNet-pytorch#7]

**Comment by dragonbook** [comment]
Comment progressbar related code in [lib/solver.py](https://github.com/dragonbook/V2V-PoseNet-pytorch/blob/c8dfb690c0733d7adae8becdd3948a8baf72e996/lib/solver.py) and [integral-pose/solver.py](https://github.com/dragonbook/V2V-PoseNet-pytorch/blob/04baee1981984d6c01ea727ffbe4ee147bbf79ac/integral-pose/solver.py), and just directly use print function(already provided).
