### ISSUE TITLE
the question of numble about dataset

### ISSUE THREAD

**Issue by Ericjiejie** [dragonbook/V2V-PoseNet-pytorch#8]
the sample numble of msra_center provided in your code dont equal msra dataset. one(msra_center) is 76391 and another(msra dataset) is 76375.

**Comment by Ericjiejie** [comment]
hi@dragonbook
can you tell me how to get those reference points of MSRA dataset? I need that,because it is mismatching to MSRA dataset downloaded from net.i'm waitting for your response

**Comment by dragonbook** [comment]
Hi, Ericjiejie,

The reference points cached in this repo are just copied from the author's [official repo](https://github.com/mks0601/V2V-PoseNet_RELEASE), as I said in README. You can get the correct MSRA dataset link and download the matching reference points data directly from there. And I guess you might download the wrong version of that dataset. You can find more information on author's repo.
