### ISSUE TITLE
Why I get an image of a hand gesture standing on its head

### ISSUE THREAD

**Issue by huangshaoguang** [dragonbook/V2V-PoseNet-pytorch#9]
Why I get an image of a hand gesture standing on its head(all the results are the same!):
![9](https://user-images.githubusercontent.com/18713992/59335509-4d37e980-8d2f-11e9-9c96-98297beabe3f.jpg)

**Comment by dragonbook** [comment]
Maybe there is a hidden mistake in your visualization pipeline, for example, when you map the rgb-d pixel to the 3d world.
